# syntax = docker/dockerfile:1

ARG NODE_VERSION=latest

FROM node:${NODE_VERSION} AS base

ARG PORT=3000

WORKDIR /src

# Build

FROM base AS build

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

# Run

FROM base

ENV PORT=$PORT

ENV NODE_ENV=production

COPY --from=build /src/.output /src/.output

CMD [ "node", ".output/server/index.mjs" ]